# Generated by Django 4.0 on 2021-12-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_meal_type_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='meals',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cost', models.FloatField()),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.meal')),
            ],
        ),
    ]
