# Generated by Django 4.0 on 2021-12-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_order_meal_order_meals_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id_meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.meal'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='meal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
