# Generated by Django 4.0 on 2021-12-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_meal_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
