# Generated by Django 4.0 on 2021-12-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
