# Generated by Django 4.0 on 2021-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_cart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost',
            new_name='costs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='meals',
            field=models.JSONField(default={}),
        ),
    ]
